<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoginMasukSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seeder untuk tb_administrator
        DB::table('tb_administrator')->insert([
            [
                'idAdministrator' => 1,
                'username' => 'admin1',
                'nama' => 'Administrator 1',
                'email' => 'admin1@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 2,
                'username' => 'admin2',
                'nama' => 'Administrator 2',
                'email' => 'admin2@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 3,
                'username' => 'admin3',
                'nama' => 'Administrator 3',
                'email' => 'admin3@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 4,
                'username' => 'admin4',
                'nama' => 'Administrator 4',
                'email' => 'admin4@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 5,
                'username' => 'admin5',
                'nama' => 'Administrator 5',
                'email' => 'admin5@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 6,
                'username' => 'admin6',
                'nama' => 'Administrator 6',
                'email' => 'admin6@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 7,
                'username' => 'admin7',
                'nama' => 'Administrator 7',
                'email' => 'admin7@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 8,
                'username' => 'admin8',
                'nama' => 'Administrator 8',
                'email' => 'admin8@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 9,
                'username' => 'admin9',
                'nama' => 'Administrator 9',
                'email' => 'admin9@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 10,
                'username' => 'admin10',
                'nama' => 'Administrator 10',
                'email' => 'admin10@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tb_dosen
        DB::table('tb_dosen')->insert([
            [
                'nik' => 113105,
                'no_telp' => '085762315262',
                'nama_dosen' => 'Supardianto, S.ST., M.Eng',
                'password' => bcrypt('dosen123'),
                'email' => 'supardianto@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 122275,
                'no_telp' => '082273083850',
                'nama_dosen' => 'Ahmadi Irmansyah Lubis, S.Kom., M.Kom.',
                'password' => bcrypt('dosen123'),
                'email' => 'ahmadi@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 113115,
                'no_telp' => '082171490817',
                'nama_dosen' => 'Sartikha, S.ST., M.Eng',
                'password' => bcrypt('dosen123'),
                'email' => 'sartikha@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 124300,
                'no_telp' => '08566575124',
                'nama_dosen' => 'Suwarno, S.S., M.Pd',
                'password' => bcrypt('dosen123'),
                'email' => 'suwarno@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 122279,
                'no_telp' => '082284070171',
                'nama_dosen' => 'Alena Uperiati, S.T, M.Cs',
                'password' => bcrypt('dosen123'),
                'email' => 'alena@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 122277,
                'no_telp' => '085376166392',
                'nama_dosen' => 'Noper Ardi, S.Pd., M.Eng',
                'password' => bcrypt('dosen123'),
                'email' => 'noper@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 100015,
                'no_telp' => '0895365618212',
                'nama_dosen' => 'Metta Santiputri, S.T., M.Sc., Ph.D',
                'password' => bcrypt('dosen123'),
                'email' => 'metta@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 102020,
                'no_telp' => '08163674205',
                'nama_dosen' => 'Hilda Widyastuti, S.T., M.T.',
                'password' => bcrypt('dosen123'),
                'email' => 'hilda@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 121246,
                'no_telp' => '081374453006',
                'nama_dosen' => 'Siskha Handayani, S.Si., M.Si',
                'password' => bcrypt('dosen123'),
                'email' => 'siskha@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 117175,
                'no_telp' => '085767687475',
                'nama_dosen' => 'Hamdani Arif, S.Pd., M.Sc',
                'password' => bcrypt('dosen123'),
                'email' => 'hamdani@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


        // Seeder untuk tb_mahasiswa
        DB::table('tb_mahasiswa')->insert([
            [
                'nim' => 4342401031,
                'judul_tugas_akhir' => 'Implementasi Sistem Informasi Akademik',
                'nama_mahasiswa' => 'Muhammad Ariq Akbari Ashar',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'ariq.akbari@example.com',
                'nik_dosen' => 113105,
                'no_telp' => '081234567891',
                'kelas' => 'TRPL 7A',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401032,
                'judul_tugas_akhir' => 'Aplikasi Penjadwalan Kelas',
                'nama_mahasiswa' => 'Christian Jeremiatur Hamonangan S',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'christian.jeremiatur@example.com',
                'nik_dosen' => 122275,
                'no_telp' => '081234567892',
                'kelas' => 'TRPL 7B',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401033,
                'judul_tugas_akhir' => 'Pengembangan Website E-Commerce',
                'nama_mahasiswa' => 'Adib Zahran',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'adib.zahran@example.com',
                'nik_dosen' => 113115,
                'no_telp' => '081234567893',
                'kelas' => 'TRPL 7C',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401034,
                'judul_tugas_akhir' => 'Sistem Pengelolaan Data Perpustakaan',
                'nama_mahasiswa' => 'Wasyn Sulaiman Siregar',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'wasyn.sulaiman@example.com',
                'nik_dosen' => 124300,
                'no_telp' => '081234567894',
                'kelas' => 'TRPL 7C',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401035,
                'judul_tugas_akhir' => 'Pengembangan Aplikasi Keuangan',
                'nama_mahasiswa' => 'Muhammad Hasan Firdaus',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'hasan.firdaus@example.com',
                'nik_dosen' => 122279,
                'no_telp' => '081234567895',
                'kelas' => 'TRPL 7A',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401036,
                'judul_tugas_akhir' => 'Sistem Informasi Perpustakaan Digital',
                'nama_mahasiswa' => 'Andri Putra Desyandra Siregar',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'andri.siregar@example.com',
                'nik_dosen' => 117175,
                'no_telp' => '081234567896',
                'kelas' => 'TRPL 7B',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401037,
                'judul_tugas_akhir' => 'Implementasi Sistem Pakar Diagnosa Penyakit',
                'nama_mahasiswa' => 'Hasna Fadhilah Ramadhan',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'hasna.ramadhan@example.com',
                'nik_dosen' => 113105,
                'no_telp' => '081234567897',
                'kelas' => 'TRPL 7A',
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401038,
                'judul_tugas_akhir' => 'Aplikasi Pemesanan Tiket Online',
                'nama_mahasiswa' => 'Veny Isnaini Prastia',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'veny.prastia@example.com',
                'nik_dosen' => 124300,
                'no_telp' => '081234567898',
                'kelas' => 'TRPL 7C',
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401039,
                'judul_tugas_akhir' => 'Sistem Manajemen Proyek',
                'nama_mahasiswa' => 'Sheila Rifqi',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'sheila.rifqi@example.com',
                'nik_dosen' => 121246,
                'no_telp' => '081234567899',
                'kelas' => 'TRPL 7B',
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401040,
                'judul_tugas_akhir' => 'Pengembangan Sistem E-Learning',
                'nama_mahasiswa' => 'Juan Immanuel Tinambunan',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'juan.tinambunan@example.com',
                'nik_dosen' => 117175,
                'no_telp' => '081234567810',
                'kelas' => 'TRPL 7C',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401045,
                'judul_tugas_akhir' => 'Sistem Pendukung Keputusan Beasiswa',
                'nama_mahasiswa' => 'Ziyadatul Khoir',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'ziyadatul.khoir@example.com',
                'nik_dosen' => 122279,
                'no_telp' => '081234567815',
                'kelas' => 'TRPL 7A',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ],
            [
                'nim' => 4342401057,
                'judul_tugas_akhir' => 'Aplikasi Penjadwalan Bimbingan',
                'nama_mahasiswa' => 'Muhammad Maulana Yusuf',
                'password' => bcrypt('mahasiswa123'),
                'email' => 'yusuf.maulana@example.com',
                'nik_dosen' => 113105,
                'no_telp' => '081234567826',
                'kelas' => 'TRPL 7B',
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
                'remember_token' => null,
                'createdByAdmin' => 1
            ]
        ]);


        // Seeder untuk tb_waktu_dosen
        DB::table('tb_waktuDosen')->insert([
            [
                'idWaktuDosen' => 1,
                'nik_dosen' => 113105,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 2,
                'nik_dosen' => 122275,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => false,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 3,
                'nik_dosen' => 113115,
                'kondisi_senin' => false,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 4,
                'nik_dosen' => 124300,
                'kondisi_senin' => true,
                'kondisi_selasa' => false,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 5,
                'nik_dosen' => 122279,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => false,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 6,
                'nik_dosen' => 122277,
                'kondisi_senin' => false,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => false,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 7,
                'nik_dosen' => 100015,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => false,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 8,
                'nik_dosen' => 102020,
                'kondisi_senin' => true,
                'kondisi_selasa' => false,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 9,
                'nik_dosen' => 121246,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => false,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 10,
                'nik_dosen' => 117175,
                'kondisi_senin' => true,
                'kondisi_selasa' => false,
                'kondisi_rabu' => true,
                'kondisi_kamis' => false,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
