<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoginMasukSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seeder untuk tb_administrator
        DB::table('tb_administrator')->insert([
            [
                'idAdministrator' => 1,
                'username' => 'admin1',
                'nama' => 'Administrator 1',
                'email' => 'admin1@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 2,
                'username' => 'admin2',
                'nama' => 'Administrator 2',
                'email' => 'admin2@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 3,
                'username' => 'admin3',
                'nama' => 'Administrator 3',
                'email' => 'admin3@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 4,
                'username' => 'admin4',
                'nama' => 'Administrator 4',
                'email' => 'admin4@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 5,
                'username' => 'admin5',
                'nama' => 'Administrator 5',
                'email' => 'admin5@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 6,
                'username' => 'admin6',
                'nama' => 'Administrator 6',
                'email' => 'admin6@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 7,
                'username' => 'admin7',
                'nama' => 'Administrator 7',
                'email' => 'admin7@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 8,
                'username' => 'admin8',
                'nama' => 'Administrator 8',
                'email' => 'admin8@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 9,
                'username' => 'admin9',
                'nama' => 'Administrator 9',
                'email' => 'admin9@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Laki-laki',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idAdministrator' => 10,
                'username' => 'admin10',
                'nama' => 'Administrator 10',
                'email' => 'admin10@example.com',
                'password' => bcrypt('password123'),
                'jenis_kelamin' => 'Perempuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tb_dosen
        DB::table('tb_dosen')->insert([
            [
                'nik' => 1234567890123456,
                'no_telp' => '0812345678901',
                'nama_dosen' => 'Dosen 1',
                'password' => bcrypt('password123'),
                'email' => 'dosen1@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123457,
                'no_telp' => '0812345678902',
                'nama_dosen' => 'Dosen 2',
                'password' => bcrypt('password123'),
                'email' => 'dosen2@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123458,
                'no_telp' => '0812345678903',
                'nama_dosen' => 'Dosen 3',
                'password' => bcrypt('password123'),
                'email' => 'dosen3@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123459,
                'no_telp' => '0812345678904',
                'nama_dosen' => 'Dosen 4',
                'password' => bcrypt('password123'),
                'email' => 'dosen4@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123460,
                'no_telp' => '0812345678905',
                'nama_dosen' => 'Dosen 5',
                'password' => bcrypt('password123'),
                'email' => 'dosen5@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123461,
                'no_telp' => '0812345678906',
                'nama_dosen' => 'Dosen 6',
                'password' => bcrypt('password123'),
                'email' => 'dosen6@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123462,
                'no_telp' => '0812345678907',
                'nama_dosen' => 'Dosen 7',
                'password' => bcrypt('password123'),
                'email' => 'dosen7@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123463,
                'no_telp' => '0812345678908',
                'nama_dosen' => 'Dosen 8',
                'password' => bcrypt('password123'),
                'email' => 'dosen8@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123464,
                'no_telp' => '0812345678909',
                'nama_dosen' => 'Dosen 9',
                'password' => bcrypt('password123'),
                'email' => 'dosen9@example.com',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => 1234567890123465,
                'no_telp' => '0812345678910',
                'nama_dosen' => 'Dosen 10',
                'password' => bcrypt('password123'),
                'email' => 'dosen10@example.com',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tb_mahasiswa
        DB::table('tb_mahasiswa')->insert([
            [
                'nim' => 1000000001,
                'judul_tugas_akhir' => 'Analisis Algoritma Machine Learning',
                'nama_mahasiswa' => 'Mahasiswa 1',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa1@example.com',
                'nik_dosen' => 1234567890123456,
                'no_telp' => '0812345678001',
                'kelas' => 'TI-1A',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000002,
                'judul_tugas_akhir' => 'Pengembangan Aplikasi Mobile',
                'nama_mahasiswa' => 'Mahasiswa 2',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa2@example.com',
                'nik_dosen' => 1234567890123457,
                'no_telp' => '0812345678002',
                'kelas' => 'TI-1B',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000003,
                'judul_tugas_akhir' => 'Sistem Informasi Geografis',
                'nama_mahasiswa' => 'Mahasiswa 3',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa3@example.com',
                'nik_dosen' => 1234567890123458,
                'no_telp' => '0812345678003',
                'kelas' => 'TI-1C',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000004,
                'judul_tugas_akhir' => 'Optimasi Jaringan Komputer',
                'nama_mahasiswa' => 'Mahasiswa 4',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa4@example.com',
                'nik_dosen' => 1234567890123459,
                'no_telp' => '0812345678004',
                'kelas' => 'TI-1D',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000005,
                'judul_tugas_akhir' => 'Keamanan Siber',
                'nama_mahasiswa' => 'Mahasiswa 5',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa5@example.com',
                'nik_dosen' => 1234567890123460,
                'no_telp' => '0812345678005',
                'kelas' => 'TI-2A',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000006,
                'judul_tugas_akhir' => 'Pengolahan Data Besar',
                'nama_mahasiswa' => 'Mahasiswa 6',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa6@example.com',
                'nik_dosen' => 1234567890123461,
                'no_telp' => '0812345678006',
                'kelas' => 'TI-2B',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000007,
                'judul_tugas_akhir' => 'Pemrograman Paralel',
                'nama_mahasiswa' => 'Mahasiswa 7',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa7@example.com',
                'nik_dosen' => 1234567890123462,
                'no_telp' => '0812345678007',
                'kelas' => 'TI-2C',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000008,
                'judul_tugas_akhir' => 'Pemrograman Blockchain',
                'nama_mahasiswa' => 'Mahasiswa 8',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa8@example.com',
                'nik_dosen' => 1234567890123463,
                'no_telp' => '0812345678008',
                'kelas' => 'TI-2D',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000009,
                'judul_tugas_akhir' => 'Analisis Sistem Cloud Computing',
                'nama_mahasiswa' => 'Mahasiswa 9',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa9@example.com',
                'nik_dosen' => 1234567890123464,
                'no_telp' => '0812345678009',
                'kelas' => 'TI-3A',
                'jenis_kelamin' => 'Laki-laki',
                'createdByAdmin' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => 1000000010,
                'judul_tugas_akhir' => 'Implementasi Sistem IoT',
                'nama_mahasiswa' => 'Mahasiswa 10',
                'password' => bcrypt('password123'),
                'email' => 'mahasiswa10@example.com',
                'nik_dosen' => 1234567890123465,
                'no_telp' => '0812345678010',
                'kelas' => 'TI-3B',
                'jenis_kelamin' => 'Perempuan',
                'createdByAdmin' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tb_waktu_dosen
        DB::table('tb_waktuDosen')->insert([
            [
                'idWaktuDosen' => 1,
                'nik_dosen' => 1234567890123456,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 2,
                'nik_dosen' => 1234567890123457,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => false,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 3,
                'nik_dosen' => 1234567890123458,
                'kondisi_senin' => false,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 4,
                'nik_dosen' => 1234567890123459,
                'kondisi_senin' => true,
                'kondisi_selasa' => false,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 5,
                'nik_dosen' => 1234567890123460,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => false,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 6,
                'nik_dosen' => 1234567890123461,
                'kondisi_senin' => false,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => false,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 7,
                'nik_dosen' => 1234567890123462,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => true,
                'kondisi_kamis' => false,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 8,
                'nik_dosen' => 1234567890123463,
                'kondisi_senin' => true,
                'kondisi_selasa' => false,
                'kondisi_rabu' => true,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 9,
                'nik_dosen' => 1234567890123464,
                'kondisi_senin' => true,
                'kondisi_selasa' => true,
                'kondisi_rabu' => false,
                'kondisi_kamis' => true,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => false,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'idWaktuDosen' => 10,
                'nik_dosen' => 1234567890123465,
                'kondisi_senin' => true,
                'kondisi_selasa' => false,
                'kondisi_rabu' => true,
                'kondisi_kamis' => false,
                'kondisi_jumat' => true,
                'kondisi_sabtu' => true,
                'kondisi_minggu' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
